export interface Project {
  slug: string;
  name: string;
  nameBn: string;
  location: string;
  locationBn: string;
  city: "Dhaka" | "Chandpur";
  status: "ongoing" | "upcoming" | "completed";
  flatSize: string;
  landArea: string;
  floors: string;
  facing: string;
  amenities: string[];
  description: string;
  descriptionBn: string;
  image: string;
  images?: string[];
  brochure?: string;
}

export const projects: Project[] = [
  {
    slug: "bondhon-tower",
    name: "Bondhon Tower",
    nameBn: "বন্ধন টাওয়ার",
    location: "Anando Nagar, Jheelpar, Hazi Wakiluddin Road, Merul Badda, Dhaka",
    locationBn: "আনন্দ নগর, ঝিলপাড়, হাজি ওয়াকিলউদ্দিন রোড, মেরুল বাড্ডা, ঢাকা",
    city: "Dhaka",
    status: "ongoing",
    flatSize: "1,350 - 1,550 sqft",
    landArea: "5 Katha",
    floors: "G+9",
    facing: "South-East",
    amenities: ["Elevator", "Generator", "Parking", "Rooftop Garden", "Security"],
    description: "A premium residential project in the heart of Aftabnagar with modern amenities and elegant design.",
    descriptionBn: "আফতাবনগরের প্রাণকেন্দ্রে আধুনিক সুযোগ-সুবিধা ও মার্জিত নকশা সহ একটি প্রিমিয়াম আবাসিক প্রকল্প।",
    image: "/S & D Bondhon Tower/S & D Bondhon Tower Chandpur.jpg",
    images: [
      "/S & D Bondhon Tower/S & D Bondhon Tower Chandpur.jpg",
      "/S & D Bondhon Tower/S & D Bondhon Tower Chandpur Top.jpg",
      "/S & D Bondhon Tower/S & D Bondhon Tower Chandpur Night View-.jpg"
    ],
    brochure: "/S & D Bondhon Tower/Bondhon Tower.pdf",
  },
  {
    slug: "laila-garden",
    name: "Laila Garden",
    nameBn: "লাইলা গার্ডেন",
    location: "Road-02, Block-C, Aftabnagar, Dhaka",
    locationBn: "রোড-০২, ব্লক-সি, আফতাবনগর, ঢাকা",
    city: "Dhaka",
    status: "completed",
    flatSize: "1,200 - 1,400 sqft",
    landArea: "6 Katha",
    floors: "G+6",
    facing: "South",
    amenities: ["Elevator", "Generator", "Parking", "Community Hall"],
    description: "A beautifully completed residential complex in Chandpur offering spacious living in a serene environment.",
    descriptionBn: "চাঁদপুরে একটি সুন্দরভাবে সম্পন্ন আবাসিক কমপ্লেক্স যা শান্ত পরিবেশে প্রশস্ত জীবনযাপনের সুযোগ দেয়।",
    image: "/S&D Laila Garden, Aftabnagar/S&D Laila Garden Aftabnagar.jpg",
    brochure: "/S&D Laila Garden, Aftabnagar/S & D___Edit.pdf",
  },
  {
    slug: "fm-tower",
    name: "F.M Tower",
    nameBn: "এফ.এম টাওয়ার",
    location: "Opposite site of Chandpur Zonal Passport Office, Faridganj Road, Chandpur",
    locationBn: "চাঁদপুর জোনাল পাসপোর্ট অফিসের বিপরীতে, ফরিদগঞ্জ রোড, চাঁদপুর",
    city: "Chandpur",
    status: "ongoing",
    flatSize: "1,100 - 1,300 sqft",
    landArea: "4.5 Katha",
    floors: "G+9",
    facing: "West",
    amenities: ["Elevator", "Generator", "Parking", "Gym", "Security"],
    description: "Modern urban living with premium finishes and strategic location near key amenities.",
    descriptionBn: "প্রধান সুবিধার কাছে কৌশলগত অবস্থান সহ প্রিমিয়াম ফিনিশিং সহ আধুনিক শহুরে জীবনযাপন।",
    image: "/S & D FM Tower/21_1 - Photo.jpg",
    brochure: "/S & D FM Tower/FM Tower Brochure.pdf",
  },
  {
    slug: "giash-garden",
    name: "Giash Garden",
    nameBn: "গিয়াশ গার্ডেন",
    location: "Road-02, Block-C, Aftabnagar, Dhaka",
    locationBn: "রোড-০২, ব্লক-সি, আফতাবনগর, ঢাকা",
    city: "Dhaka",
    status: "completed",
    flatSize: "1,250 - 1,500 sqft",
    landArea: "7 Katha",
    floors: "G+6",
    facing: "North-South",
    amenities: ["Elevator", "Generator", "Parking", "Playground", "Rooftop Garden"],
    description: "An upcoming landmark project in Chandpur with spacious apartments and lush green surroundings.",
    descriptionBn: "চাঁদপুরে প্রশস্ত অ্যাপার্টমেন্ট এবং সবুজ পরিবেশ সহ একটি আসন্ন ল্যান্ডমার্ক প্রকল্প।",
    image: "/S & D Giash Garden/S&D View.jpg",
  },
  {
    slug: "safura-heights",
    name: "Safura Heights",
    nameBn: "সাফুরা হাইটস",
    location: "Road-06, Block-H, Aftabnagar, Dhaka",
    locationBn: "রোড-০৬, ব্লক-এইচ, আফতাবনগর, ঢাকা",
    city: "Dhaka",
    status: "completed",
    flatSize: "1,400 - 1,600 sqft",
    landArea: "5.5 Katha",
    floors: "G+6",
    facing: "East",
    amenities: ["Elevator", "Generator", "Parking", "Swimming Pool", "Gym", "Security"],
    description: "A prestigious completed project offering luxury living with world-class amenities.",
    descriptionBn: "বিশ্বমানের সুবিধা সহ বিলাসবহুল জীবনযাপনের প্রস্তাব দেওয়া একটি মর্যাদাপূর্ণ সম্পন্ন প্রকল্প।",
    image: "/S&D Safura Heights, Aftabnagar/1.6  Regular edited.jpg",
    brochure: "/S&D Safura Heights, Aftabnagar/Safura Heights-.pdf",
  },
  {
    slug: "sardar-palace",
    name: "Sardar Palace",
    nameBn: "সর্দার প্যালেস",
    location: "Guakhula Road, Chandpur",
    locationBn: "গুয়াখোলা রোড, চাঁদপুর",
    city: "Chandpur",
    status: "completed",
    flatSize: "1,300 - 1,450 sqft",
    landArea: "6 Katha",
    floors: "G+6",
    facing: "South-West",
    amenities: ["Elevator", "Generator", "Parking", "Community Hall"],
    description: "A regal residential project reflecting elegance and comfort in the heart of Chandpur.",
    descriptionBn: "চাঁদপুরের প্রাণকেন্দ্রে কমনীয়তা এবং আরামের প্রতিফলন করা একটি রাজকীয় আবাসিক প্রকল্প।",
    image: "/S & D Sardar Palace,  Chandpur/S & D Sardar Palace Chandpur.jpg",
    images: [
      "/S & D Sardar Palace,  Chandpur/S & D Sardar Palace Chandpur.jpg",
      "/S & D Sardar Palace,  Chandpur/S & D Sardar Palace Chandpur Top.jpg",
      "/S & D Sardar Palace,  Chandpur/S & D Sardar Palace Chandpur Top NIGHT VIEW.jpg"
    ],
    brochure: "/S & D Sardar Palace,  Chandpur/Sarder Palace Outline.pdf",
  },
  {
    slug: "didar-box",
    name: "Didar Box",
    nameBn: "দিদার বক্স",
    location: "Back side of Modina Shopping Center, Kalibari Mor, Chandpur",
    locationBn: "মদিনা শপিং সেন্টারের পেছনে, কালীবাড়ি মোড়, চাঁদপুর",
    city: "Chandpur",
    status: "ongoing",
    flatSize: "1,200 - 1,500 sqft",
    landArea: "4 Katha",
    floors: "G+6",
    facing: "East",
    amenities: ["Elevator", "Generator", "Parking", "Security"],
    description: "A modern upcoming project blending functionality with aesthetics.",
    descriptionBn: "নান্দনিকতার সাথে কার্যকারিতার মিশ্রণকারী একটি আধুনিক আসন্ন প্রকল্প।",
    image: "/S & D Didar Box/Final (1).jpg",
    images: ["/S & D Didar Box/Final (1).jpg"],
    brochure: "/S & D Didar Box/Didar Box Brochure Final.pdf",
  },
  {
    slug: "hossen-vill",
    name: "Hossain Villa",
    nameBn: "হোসাইন ভিলা",
    location: "Ukilpara Hardyal Road, Natun Bazar, Chandpur",
    locationBn: "উকিলপাড়া হারডিয়াল রোড, নতুন বাজার, চাঁদপুর",
    city: "Chandpur",
    status: "ongoing",
    flatSize: "1,300 - 1,600 sqft",
    landArea: "5 Katha",
    floors: "G+6",
    facing: "South",
    amenities: ["Elevator", "Generator", "Parking", "Security"],
    description: "A serene residential villa located in the heart of Chandpur.",
    descriptionBn: "চাঁদপুরের প্রাণকেন্দ্রে অবস্থিত একটি শান্ত আবাসিক ভিলা।",
    image: "/S & D Hossen Vill/1_2 - Photo01.jpg",
    images: ["/S & D Hossen Vill/1_2 - Photo01.jpg"],
    brochure: "/S & D Hossen Vill/Broshure SND Mithu Chandpur.pdf",
  },
  {
    slug: "majeda-garden",
    name: "Majeda Garden",
    nameBn: "মাজেদা গার্ডেন",
    location: "Taltola, Chandpur",
    locationBn: "টালটলা, চাঁদপুর",
    city: "Chandpur",
    status: "completed",
    flatSize: "1,400 - 1,700 sqft",
    landArea: "6 Katha",
    floors: "G+9",
    facing: "North",
    amenities: ["Elevator", "Generator", "Parking", "Playground"],
    description: "A beautiful residential sanctuary offering lush gardens and premium facilities.",
    descriptionBn: "বিলাসবহুল বাগান এবং প্রিমিয়াম সুবিধা প্রদানকারী একটি সুন্দর আবাসিক অভয়ারণ্য।",
    image: "/S & D Majeda Garden, Chandpur/S & D Majeda Garden Chandpur.jpg",
    images: ["/S & D Majeda Garden, Chandpur/S & D Majeda Garden Chandpur.jpg"],
    brochure: "/S & D Majeda Garden, Chandpur/majeda broshior/1-16.jpg",
  },
  {
    slug: "nurjahan-palace",
    name: "Nurjahan Palace",
    nameBn: "নূরজাহান প্যালেস",
    location: "Jor Pukur Par, Chandpur",
    locationBn: "জোড় পুকুর পাড়, চাঁদপুর",
    city: "Chandpur",
    status: "completed",
    flatSize: "1,250 - 1,450 sqft",
    landArea: "5.5 Katha",
    floors: "G+6",
    facing: "West",
    amenities: ["Elevator", "Generator", "Parking", "Security"],
    description: "Experience royal living with modern amenities in Chandpur.",
    descriptionBn: "চাঁদপুরে আধুনিক সুযোগ-সুবিধা সহ রাজকীয় জীবনযাপনের অভিজ্ঞতা নিন।",
    image: "/S & D Nurjahan Palace, Chandpur/1_3 - Photo.jpg",
    images: ["/S & D Nurjahan Palace, Chandpur/1_3 - Photo.jpg"],
    brochure: "/S & D Nurjahan Palace, Chandpur/Nurjahan Palace Outline.pdf",
  },
  {
    slug: "shohodora-palace",
    name: "Shohodora Palace",
    nameBn: "সহোদরা প্যালেস",
    location: "Nabinbag, Khilgaon, Dhaka",
    locationBn: "নবীনবাগ, খিলগাঁও, ঢাকা",
    city: "Dhaka",
    status: "upcoming",
    flatSize: "1,150 - 1,350 sqft",
    landArea: "4.5 Katha",
    floors: "G+6",
    facing: "South-East",
    amenities: ["Elevator", "Generator", "Parking", "Community Hall"],
    description: "A well-designed completed project offering comfort and security.",
    descriptionBn: "আরাম এবং নিরাপত্তা প্রদানকারী একটি সু-নকশাকৃত সম্পন্ন প্রকল্প।",
    image: "/S & D Shohodora Palace/141.png",
    images: ["/S & D Shohodora Palace/141.png"],
    brochure: "/S & D Shohodora Palace/Broshure Shohodora Palace.pdf",
  },
  {
    slug: "rouf-garden",
    name: "Rouf Garden",
    nameBn: "রউফ গার্ডেন",
    location: "Block-F, Aftabnagar, Dhaka",
    locationBn: "ব্লক-এফ, আফতাবনগর, ঢাকা",
    city: "Dhaka",
    status: "upcoming",
    flatSize: "",
    landArea: "",
    floors: "G+8",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "sufia-monjil",
    name: "Sufia Monjil",
    nameBn: "সুফিয়া মঞ্জিল",
    location: "Plot-6228, Block-N, Road-52, Bashundhara (R/A), Dhaka",
    locationBn: "প্লট-৬২২৮, ব্লক-এন, রোড-৫২, বসুন্ধরা (আর/এ), ঢাকা",
    city: "Dhaka",
    status: "upcoming",
    flatSize: "",
    landArea: "",
    floors: "G+6",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "j-f-tower",
    name: "J.F Tower",
    nameBn: "জে.এফ টাওয়ার",
    location: "Block-D, Aftabnagar, Dhaka",
    locationBn: "ব্লক-ডি, আফতাবনগর, ঢাকা",
    city: "Dhaka",
    status: "ongoing",
    flatSize: "",
    landArea: "",
    floors: "G+8",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "zahir-mansion",
    name: "Zahir Mansion",
    nameBn: "জাহির ম্যানশন",
    location: "Plot-2005, Block-M, Road-30, Bashundhara(R/A), Dhaka",
    locationBn: "প্লট-২০০৫, ব্লক-এম, রোড-৩০, বসুন্ধরা (আর/এ), ঢাকা",
    city: "Dhaka",
    status: "ongoing",
    flatSize: "",
    landArea: "",
    floors: "G+8",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "rajia-mansion",
    name: "Rajia Mansion",
    nameBn: "রাজিয়া ম্যানশন",
    location: "Guakhula Road, Chandpur",
    locationBn: "গুয়াখোলা রোড, চাঁদপুর",
    city: "Chandpur",
    status: "upcoming",
    flatSize: "",
    landArea: "",
    floors: "G+7",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "sonali-kuitir",
    name: "Sonali Kuitir",
    nameBn: "সোনালী কুঠির",
    location: "Opposite site of DC Office & Chief Judicial Magistrate Court Chandpur Sadar, Chandpur",
    locationBn: "ডিসি অফিস ও চিফ জুডিশিয়াল ম্যাজিস্ট্রেট কোর্টের বিপরীতে, চাঁদপুর সদর, চাঁদপুর",
    city: "Chandpur",
    status: "ongoing",
    flatSize: "",
    landArea: "",
    floors: "G+8",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
  {
    slug: "rahima-palace",
    name: "Rahima Palace",
    nameBn: "রাহিমা প্যালেস",
    location: "Opposite site of Superindent of Police Chandpur Sadar, Chandpur",
    locationBn: "পুলিশ সুপারিনটেনডেন্টের বিপরীতে, চাঁদপুর সদর, চাঁদপুর",
    city: "Chandpur",
    status: "ongoing",
    flatSize: "",
    landArea: "",
    floors: "G+6",
    facing: "",
    amenities: [],
    description: "",
    descriptionBn: "",
    image: "",
    images: [],
  },
];
