/**
 * Runtime project catalog.
 *
 * The structured data lives in `projects.json`, which is generated locally by
 * `npm run extract` (see `scripts/extract-brochure.ts`) and is gitignored —
 * the PDFs it derives from are too heavy to ship through Vercel. This module
 * re-exports the JSON as a typed array and bridges the extractor's
 * `ProjectBrochure` shape onto the frontend's `Project` shape.
 *
 * `Project` is a superset of the legacy interface previously declared inline
 * in `projects-data.ts`: every old consumer (`ProjectDetail`, `FeaturedProjects`,
 * `Projects`) keeps working, and new At-a-Glance fields (`landSize`,
 * `buildingHeight`, `flatSizes`, `brochureUrl`) are available everywhere.
 */

// Type-only re-import so the extractor schema and the frontend stay in sync
// without a runtime cycle.
import type { ProjectBrochure } from "./types";
// `projects.json` is generated by `npm run extract` (gitignored). The build
// will fail with a clear "Could not resolve ./projects.json" error if you
// forget to run extract first — that's intentional. See README > Development.
import projectsJson from "./projects.json";

type City = "Dhaka" | "Chandpur";
type Status = "ongoing" | "upcoming" | "completed";

export interface Project {
  slug: string;
  name: string;
  nameBn: string;
  location: string;
  locationBn: string;
  city: City;
  status: Status;

  /** Legacy string field ("1130, 1420 sft"). Kept for backward compat. */
  flatSize: string;
  /** Legacy string field ("5 Katha"). Kept for backward compat. */
  landArea: string;
  /** Legacy string field ("G+9"). Kept for backward compat. */
  floors: string;
  facing: string;
  amenities: string[];
  description: string;
  descriptionBn: string;
  image: string;
  images?: string[];

  // --- Legacy brochure field (external URL). Superseded by `brochureUrl` ---
  /** @deprecated use `brochureUrl`. */
  brochure?: string;

  // --- New At-a-Glance fields (from extractor) ---
  /** Land size as a structured value, e.g. { value: 5, unit: "Katha" }. */
  landSize?: { value: number; unit: string };
  /** Building height in floors, e.g. 9 (parsed from "G+9"). */
  buildingHeight?: number;
  /** Flat sizes as a list of square-foot numbers, e.g. [1130, 1420]. */
  flatSizes?: number[];
  /** External URL to the full PDF brochure (Vercel Blob / GitHub Releases). */
  brochureUrl?: string;
  /** Local path to the optimized cover image (e.g., "/covers/slug.webp"). */
  coverImage?: string;
  /** Handover date as free text (e.g. "Dec 2026"). */
  handover?: string;
  /** Google Maps embed URL derived from the location string. */
  mapEmbedUrl?: string;
}

/** Normalize a raw extractor record onto the `Project` shape. */
function adapt(raw: ProjectBrochure): Project {
  // landArea -> landSize { value, unit }
  const landMatch = raw.landArea?.match(/([\d.]+)\s*([A-Za-z\u0980-\u09FF]+)/);
  const landSize = landMatch
    ? { value: parseFloat(landMatch[1]), unit: landMatch[2] }
    : undefined;

  // floors "G+9" -> buildingHeight 9
  const gplus = raw.floors?.match(/G\s*\+\s*(\d+)/i);
  const storied = raw.floors?.match(/(\d+)\s*storied/i);
  const buildingHeight = gplus
    ? Number(gplus[1])
    : storied
    ? Number(storied[1])
    : undefined;

  // flatSize "1130, 1420 sft" -> flatSizes [1130, 1420]
  const flatSizes = (raw.flatSize?.match(/\d{3,4}/g) ?? []).map(Number);

  // Prefer the explicit external URL; fall back to legacy `brochure` if present.
  // (ProjectBrochure from the extractor only carries `brochureUrl`.)
  const brochureUrl = raw.brochureUrl;

  return {
    slug: raw.slug,
    name: raw.name,
    nameBn: raw.nameBn,
    location: raw.location,
    locationBn: raw.locationBn,
    city: raw.city,
    status: raw.status,
    flatSize: raw.flatSize,
    landArea: raw.landArea,
    floors: raw.floors,
    facing: raw.facing,
    amenities: raw.amenities ?? [],
    description: raw.description,
    descriptionBn: raw.descriptionBn,
    // Prefer the optimized webp cover; fall back to the raw image field if the
    // extractor couldn't render one (e.g. canvas pkg missing).
    image: raw.coverImage || raw.image || "",
    images: raw.images && raw.images.length > 0 ? raw.images : raw.coverImage ? [raw.coverImage] : raw.image ? [raw.image] : undefined,
    brochure: brochureUrl, // legacy field stays populated for old consumers
    landSize,
    buildingHeight,
    flatSizes,
    brochureUrl,
    coverImage: raw.coverImage || raw.image || "",
    handover: raw.handover,
    mapEmbedUrl: raw.mapEmbedUrl,
  };
}

/**
 * Resolve the display image for a project with cascading fallback:
 * coverImage -> image -> first images[] entry -> "".
 * Returns "" when nothing is available so callers can render the placeholder.
 *
 * The result is URL-encoded so paths containing spaces / `&` / commas
 * (e.g. `/S & D FM Tower/21_1 - Photo.jpg`) load correctly. We skip encoding
 * for paths that already look encoded (contain `%20`) or are absolute URLs.
 */
export function getImage(p: Pick<Project, "coverImage" | "image" | "images">): string {
  const raw = p.coverImage || p.image || (Array.isArray(p.images) ? p.images[0] : "") || "";
  if (!raw) return "";
  // Already absolute URL (http/https) or already encoded — leave as-is.
  if (/^https?:\/\//i.test(raw) || raw.includes("%20")) return raw;
  // Root-relative path → encode the path portion only (preserve leading `/`).
  if (raw.startsWith("/")) return "/" + encodeURI(raw.slice(1));
  return encodeURI(raw);
}

export const projects: Project[] = (projectsJson as ProjectBrochure[]).map(adapt);

/** Look up a single project by slug. */
export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
